### PR TITLE
loosen payload type requirement

### PR DESCRIPTION
**Pull request by jackyzha0**
supersedes https://github.com/replit/river/pull/92

### CODE REVIEW

**Review by masad-frost — APPROVED** [review]
【﻿ｂａｓｅｄ】


image

**Comment by masad-frost** [comment]
Probably nothing wrong with non-object schemas

**Comment by jackyzha0** [comment]
> Probably nothing wrong with non-object schemas

yeah we'll probably want to make sure codegen still works with this but otherwise seems fine 🤷

**Comment by masad-frost** [comment]
Only thing is that we run into the off chance of something inventing a type that's not serializable to json schema

**Comment by jackyzha0** [comment]
> Only thing is that we run into the off chance of something inventing a type that's not serializable to json schema

i believe everything `TSchema` represents can be serialized into json schema? 👀

**Comment by bradymadden97** [comment]
This will be better for agent RPCs too. Less tokens, less complexity building the types, etc.

**Pull request merged**
